### ISSUE TITLE
Message history

### ISSUE THREAD

**Issue by PenT1x** [Fesaa/Chat-Utilities#2]
It shouldn't add a message to message history if it is already set not to by another addon.
When another addon does `Laby.references().chatExecutor().chat(msg, false)` it should not be added to message history, but if you also have this addon on. Then it is still being added to message history.

**Comment by Fesaa** [comment]
Okey, I may have fixed it in that commit. But I'm really not doing anything weird with the event. Can you check if that fixed it for you?

**Comment by Fesaa** [comment]
The addon is also for all version, so not sure why it would only cause issues on some with the exact same code...

**Comment by Fesaa** [comment]
Okey, I don't think it fixed it

**Comment by Fesaa** [comment]
See Laby dev dc 😔
